# Generated by Django 5.0.3 on 2024-03-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=20)),
                ('customer_last_name', models.CharField(max_length=20)),
                ('customer_address', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone_no', models.IntegerField()),
                ('check_in', models.DateField(auto_now_add=True)),
                ('check_out', models.DateField(auto_now=True)),
            ],
        ),
    ]
